### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by nebi-frame** [vitalets/webrtc-ips#2]
Hi, do you guys think to add support for safari ?

**Comment by vitalets** [comment]
Just tested [demo](https://vitalets.github.io/webrtc-ips/demo/) on ios safari 12 - it does not work: no IPs found.
Although safari [declares support of WebRTC since 11](https://caniuse.com/#search=webrtc) as far as i remember there was some missing thing for detecting IP.
It would be great if someone make actual research of what is missing. And maybe we can fix it.

**Comment by vitalets** [comment]
Now it works in Safari. But you need to manually enable flag in developer menu
![image](https://user-images.githubusercontent.com/1473072/106584660-800fa080-6557-11eb-96da-74d1a7ca5bb6.png)

Result on [demo](https://vitalets.github.io/webrtc-ips/demo/):
![image](https://user-images.githubusercontent.com/1473072/106584615-75550b80-6557-11eb-9b06-1d49815c3fc3.png)
